default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: grocery_list_development

test:
  <<: *default
  database: grocery_list_test

production:
  <<: *default
  database: grocery_list_production
